pipelines:
  - name: matrix_single_dimension_pipeline
    steps:
      - name: step_1_matrix_example
        type: Matrix
        stepMode: Bash
        configuration:
          multiNode: true
        stepletMultipliers:
          nodePools:
            - ubuntu_18
          environmentVariables:
            - foo: foo
            - bar: bar
        execution:
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
