pipelines:
  - name: matrix_single_dimension_pipeline
    steps:
      - name: step_1_matrix_example
        type: Matrix
        stepMode: Bash
        configuration:
          multiNode: true
        stepletMultipliers:
          nodePools:
            - default-dynamic-nodepool
            - akhilwindows
          environmentVariables:
            - foo: foo
            - bar: bar
              runtimes:
                - type: image
                  image:
                    auto:
                      language: node
                      versions:
                        - 12
                - type: image
                  image:
                    auto:
                      language: node
                      versions:
                        - 8.17.0
        execution:
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
